<%@ Page Language="C#" AutoEventWireup="true" CodeFile="EditDatabase.aspx.cs" Inherits="EditDatabase" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Edit Database</title>
    <link rel="stylesheet" href="styles/PrimaryStyleSheet.css" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div id="wrapper">
        <div id="header">
            <span id="header-text">PARK TUDOR CHEMICAL DATABASE</span> <a href="Database.aspx" id="left-item"
                class="navi-item"><</a>
        </div>
        <div id="grid-view-wrapper">
            <div id="grid-view-scroll">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True" CellPadding="0" ForeColor="#333333" 
                AllowSorting="True" AutoGenerateColumns="False" CssClass="edit-table" 
                DataKeyNames="ID" DataSourceID="AccessDataSource1">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:TemplateField HeaderText="ID" InsertVisible="False" SortExpression="ID">
                        <EditItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Eval("ID") %>'></asp:Label>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="ID" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                ID</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("ID") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Chemical_Name" SortExpression="Chemical_Name">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server" Height="20px" 
                                Text='<%# Bind("Chemical_Name") %>' Width="150px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Chemical_Name" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                Chemical Name</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("Chemical_Name") %>'
                            Width="150px"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Amount" SortExpression="Amount">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox11" runat="server" Height="20px" 
                                Text='<%# Bind("Amount") %>' Width="45px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Amount" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                Amount</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label12" runat="server" Text='<%# Bind("Amount") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Original_Amount" 
                        SortExpression="Original_Amount">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox9" runat="server" Height="20px" 
                                Text='<%# Bind("Original_Amount") %>' Width="45px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Original_Amount" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                Original</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label10" runat="server" Text='<%# Bind("Original_Amount") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Units" SortExpression="Units">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox8" runat="server" Height="20px" 
                                Text='<%# Bind("Units") %>' Width="30px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Units" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                Units</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label9" runat="server" Text='<%# Bind("Units") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Concentration" SortExpression="Concentration">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox10" runat="server" Height="20px" 
                                Text='<%# Bind("Concentration") %>' Width="50px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Concentration" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                [ ]</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label11" runat="server" Text='<%# Bind("Concentration") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Class" SortExpression="Class">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox2" runat="server" Height="20px" 
                                Text='<%# Bind("Class") %>' Width="125px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Class" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                Class</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Bind("Class") %>' Width="125px"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Form" SortExpression="Form">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox3" runat="server" Height="20px" 
                                Text='<%# Bind("Form") %>' Width="85px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Form" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                Form</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label4" runat="server" Text='<%# Bind("Form") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Family" SortExpression="Family">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox4" runat="server" Height="20px" 
                                Text='<%# Bind("Family") %>' Width="85px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Family" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                Family</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label5" runat="server" Text='<%# Bind("Family") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Hazard_Code" SortExpression="Hazard_Code">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox5" runat="server" Height="20px" 
                                Text='<%# Bind("Hazard_Code") %>' Width="50px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Hazard_Code" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                MSDS</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label6" runat="server" Text='<%# Bind("Hazard_Code") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Disposal_Code" SortExpression="Disposal_Code">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox7" runat="server" Height="20px" 
                                Text='<%# Bind("Disposal_Code") %>' Width="50px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Disposal_Code" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                Disposal</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label8" runat="server" Text='<%# Bind("Disposal_Code") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Purchase_Date" SortExpression="Purchase_Date">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox6" runat="server" Height="20px" 
                                Text='<%# Bind("Purchase_Date") %>' Width="100px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Purchase_Date" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                Purchase Date</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label7" runat="server" 
                                Text='<%# Bind("Purchase_Date", "{0:d}") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Loc" SortExpression="Location_ID">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox13" runat="server" Height="21px" 
                                Text='<%# Bind("Location_ID") %>' Width="15px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Location_ID" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                Loc</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label14" runat="server" Text='<%# Bind("Location_ID") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Checksum" SortExpression="Checksum">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox12" runat="server" Height="21px" 
                                Text='<%# Bind("Checksum") %>' Width="36px"></asp:TextBox>
                        </EditItemTemplate>
                        <HeaderTemplate>
                            <asp:LinkButton ID="Checksum" runat="server" CssClass="header-link" OnClick="Sort_Click">
                                CKS</asp:LinkButton>
                        </HeaderTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label13" runat="server" Text='<%# Bind("Checksum") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
            <asp:AccessDataSource ID="AccessDataSource1" runat="server" 
                DataFile="~/App_Data/Database.accdb" 
                DeleteCommand="DELETE FROM [Chemicals] WHERE [ID] = ?" 
                InsertCommand="INSERT INTO [Chemicals] ([ID], [Chemical_Name], [Class], [Form], [Family], [Hazard_Code], [Disposal_Code], [Units], [Original_Amount], [Concentration], [Amount], [Checksum], [Purchase_Date], [Location_ID]) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)" 
                SelectCommand="SELECT [ID], [Chemical_Name], [Class], [Form], [Family], [Hazard_Code], [Disposal_Code], [Units], [Original_Amount], [Concentration], [Amount], [Checksum], [Purchase_Date], [Location_ID] FROM [Chemicals] ORDER BY [ID]" 
                
                    
                    UpdateCommand="UPDATE [Chemicals] SET [Chemical_Name] = ?, [Class] = ?, [Form] = ?, [Family] = ?, [Hazard_Code] = ?, [Disposal_Code] = ?, [Units] = ?, [Original_Amount] = ?, [Concentration] = ?, [Amount] = ?, [Checksum] = ?, [Purchase_Date] = ?, [Location_ID] = ? WHERE [ID] = ?">
                <DeleteParameters>
                    <asp:Parameter Name="ID" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="ID" Type="Int32" />
                    <asp:Parameter Name="Chemical_Name" Type="String" />
                    <asp:Parameter Name="Class" Type="String" />
                    <asp:Parameter Name="Form" Type="String" />
                    <asp:Parameter Name="Family" Type="String" />
                    <asp:Parameter Name="Hazard_Code" Type="String" />
                    <asp:Parameter Name="Disposal_Code" Type="String" />
                    <asp:Parameter Name="Units" Type="String" />
                    <asp:Parameter Name="Original_Amount" Type="Double" />
                    <asp:Parameter Name="Concentration" Type="Double" />
                    <asp:Parameter Name="Amount" Type="Double" />
                    <asp:Parameter Name="Checksum" Type="String" />
                    <asp:Parameter Name="Purchase_Date" Type="DateTime" />
                    <asp:Parameter Name="Location_ID" Type="Int32" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Chemical_Name" Type="String" />
                    <asp:Parameter Name="Class" Type="String" />
                    <asp:Parameter Name="Form" Type="String" />
                    <asp:Parameter Name="Family" Type="String" />
                    <asp:Parameter Name="Hazard_Code" Type="String" />
                    <asp:Parameter Name="Disposal_Code" Type="String" />
                    <asp:Parameter Name="Units" Type="String" />
                    <asp:Parameter Name="Original_Amount" Type="Double" />
                    <asp:Parameter Name="Concentration" Type="Double" />
                    <asp:Parameter Name="Amount" Type="Double" />
                    <asp:Parameter Name="Checksum" Type="String" />
                    <asp:Parameter Name="Purchase_Date" Type="DateTime" />
                    <asp:Parameter Name="Location_ID" Type="Int32" />
                    <asp:Parameter Name="ID" Type="Int32" />
                </UpdateParameters>
            </asp:AccessDataSource>
            </div>
        </div>
    </div>
    </form>
</body>
</html>
